/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuAdaFruitGfx.h"

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // contains app name and ID

// Global variables that need exporting

extern Adafruit_SSD1351 display;
extern AdafruitDrawable displayDrawable;
extern GraphicsDeviceRenderer renderer;

// Global Menu Item exports

extern ActionMenuItem menuBackToWork;
extern EnumMenuItem menuWhen;
extern AnalogMenuItem menutalkInterval;
extern BackMenuItem menuBackTalk;
extern SubMenuItem menuTalk;
extern EnumMenuItem menuTriggerMode;
extern EnumMenuItem menuCutOffLevel;
extern EnumMenuItem menuWarnAt;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern EnumMenuItem menuMode;

// Provide a wrapper to get hold of the root menu item
inline MenuItem& rootMenuItem() { return menuMode; }

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onCutOffLevelChange(int id);
void CALLBACK_FUNCTION onBackToWork(int id);
void CALLBACK_FUNCTION onModeChange(int id);
void CALLBACK_FUNCTION onTalkConditionChange(int id);
void CALLBACK_FUNCTION onTalkIntervalChange(int id);
void CALLBACK_FUNCTION onTriggerModeChange(int id);
void CALLBACK_FUNCTION onWarningLevelChange(int id);

#endif // MENU_GENERATED_CODE_H
